# Generated by Django 4.2.7 on 2024-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlisting',
            old_name='make',
            new_name='name',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
