# Generated by Django 4.2.7 on 2024-05-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAPI', '0002_rename_make_carlisting_name_carlisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='image',
        ),
    ]
